name: Maven build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-v17-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-v17

      - name: Build
        run: mvn --batch-mode compile

      - name: Test
        run: |
          mvn --batch-mode verify install
          cd tests/quarkus-tests
          mvn --batch-mode test
